import Head from "next/head";
import Navigation from "../components/navigation/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>QM Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
    </div>
  );
}
